// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Database.Models.Map", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeatmapsetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MapperId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OsuModificationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("MapId");

                    b.HasIndex("MapperId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Database.Models.Mapper", b =>
                {
                    b.Property<int>("MapperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("MapperId");

                    b.ToTable("Mappers");
                });

            modelBuilder.Entity("Database.Models.Nominator", b =>
                {
                    b.Property<int>("NominatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("NominatorId");

                    b.ToTable("Nominators");
                });

            modelBuilder.Entity("MapNominator", b =>
                {
                    b.Property<int>("MapsMapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NominatorsNominatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MapsMapId", "NominatorsNominatorId");

                    b.HasIndex("NominatorsNominatorId");

                    b.ToTable("MapNominator");
                });

            modelBuilder.Entity("Database.Models.Map", b =>
                {
                    b.HasOne("Database.Models.Mapper", "Mapper")
                        .WithMany("Maps")
                        .HasForeignKey("MapperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapper");
                });

            modelBuilder.Entity("MapNominator", b =>
                {
                    b.HasOne("Database.Models.Map", null)
                        .WithMany()
                        .HasForeignKey("MapsMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Nominator", null)
                        .WithMany()
                        .HasForeignKey("NominatorsNominatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.Mapper", b =>
                {
                    b.Navigation("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
